// packages/create-cosmo-widget/templates/template-react-ts/src/Widget.tsx


import { useEffect } from 'react'

interface WidgetProps {
  preferences: Record<string, any>;
  widgetData: Record<string, any>;
}

export default function Widget({ preferences, widgetData }: WidgetProps) {
  useEffect(() => {
    const root = document.getElementById('widget-root');
    if (root) {
      if (preferences?.hideBackground) {
        root.classList.add('hide-background');
      } else {
        root.classList.remove('hide-background');
      }
    }
  }, [preferences?.hideBackground]);

  return (
    <div>
      <div className="header"></div>
      <div className="content">
        <h2>Preferences</h2>
        <pre>{JSON.stringify(preferences, null, 2)}</pre>
        <h2>Widget Data</h2>
        <pre>{JSON.stringify(widgetData, null, 2)}</pre>
      </div>
    </div>
  )
}

// packages/create-cosmo-widget/templates/template-vue-ts/src/Widget.vue
<script setup lang="ts">
import { watch, onMounted } from 'vue'

const props = defineProps<{
  preferences: Record<string, any>;
  widgetData?: Record<string, any>;
}>()

function updateBackgroundClass() {
  const root = document.getElementById('widget-root');
  if (root) {
    if (props.preferences?.hideBackground) {
      root.classList.add('hide-background');
    } else {
      root.classList.remove('hide-background');
    }
  }
}

onMounted(() => {
  updateBackgroundClass();
})

watch(() => props.preferences?.hideBackground, () => {
  updateBackgroundClass();
})
</script>

<template>
  <div class="widget">
    <div class="header"></div>
    <div class="content">
      <h2>Preferences</h2>
      <pre>{{ JSON.stringify(preferences, null, 2) }}</pre>
      <h2>Widget Data</h2>
      <pre>{{ JSON.stringify(widgetData, null, 2) }}</pre>
    </div>
  </div>
</template>

<style scoped>
.widget {
  width: 100%;
  height: 100%;
}

.header {
  width: 100%;
  height: 20px;
}

.content {
  width: 100%;
  height: calc(100% - 20px);
  box-sizing: border-box;
  padding: 1rem;
}

pre {
  background: #f5f5f5;
  padding: 1rem;
  border-radius: 8px;
  overflow: auto;
  font-size: 12px;
}
</style>
